### ISSUE TITLE
Excessive decimals on ping numbers

### ISSUE THREAD

**Issue by sxflynn** [benhansen-io/pinging#24]
I'm seeing excessive decimal numbers on the ping statistic. ![image](https://github.com/benhansen-io/pinging/assets/2034081/c8ddd46e-7518-473e-9b75-9eca57b960cd)

![image](https://github.com/benhansen-io/pinging/assets/2034081/ed115d47-b85b-4a58-acb0-b6edc54fa7cd)

Limiting the decimal numbers to round up to the 3rd place would be a UI improvement.

**Comment by benhansen-io** [comment]
Thanks so much for the report! I don't see this on Firefox or Chromium on Linux so must be some platform or browser specific behavior. I have deployed the fix to all three regions so let me know if you still see the issue after a refresh in an hour or so. Thanks

**Comment by sxflynn** [comment]
Looks great! I would have done the PR myself except I'm travelling with family now. I've installed your site as a homescreen app on my relatives phones so they know if their spotty internet is having problems.
