### ISSUE TITLE
Use 2 digit precision

### ISSUE THREAD

**Issue by ELC** [benhansen-io/pinging#25]
I believe it would be great to show the Packet Loss with two digits precision so that we can interpret it as an SLA 99.xx%

For good and healthy connections the percentage quickly goes to 0% and even if there is some packets lost, it is not enough to reach near the 0.5% needed to change the rounding.

Could you add this feature or make it user defined?

Thanks in advance, I have this pin in my browser at all times!

**Comment by benhansen-io** [comment]
Good idea. Done. You should see the change now after a cache clearing refresh.

**Comment by benhansen-io** [comment]
Also always curious to hear how people found the site if you don't mind sharing.

**Comment by ELC** [comment]
I got to know the page by reading the newletter: "Your Linux and Technology Insights 2024-06-24" from LinuxBlog.io (formerly haydenjames.io)
